Create Table MovimentacaoAtivo(
	IdMovimentacaoAtivo int primary key not null identity(1,1),
	IdMovimentacaoAtivoStatus int not null,								
	IDTransacaoAtivo	int not null,
	IDAtivo	int not null,
	IDPerfilLancamento int not null,
	IDCliente	int not null,
	IDFornecedor	int not null,
	Convencao	int null,
	DataUltimaDepreciacao	datetime not null,
	DataExecucaoDepreciacao	datetime not null,
	Depreciacao	int null,
	IDGrupoAtivo	int not null,
	PermitirValorNegativo int null,
	Periodo	int not null,
	PeriodoDepreciacaoRestante	int not null,
	ValorAquisicao	decimal(18,4) null,
	RevisaoAquisicao	decimal(18,4) null,
	StatusAtivo	int null,
	ValorSucata	decimal(18,4) null,
	ValorVenda	decimal(18,4) null,
	ValorICMS	decimal(18,4) null,
	VidaUtil	decimal(18,4) null,
	DataTrasacao	datetime not null,
	DataDocumento	datetime not null,
	NotaFiscal	varchar(255) null,
	NivelLancamento	int null
)