SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PedidoCompraCentroCusto](
	[IdPedidoCompraCentroCusto] [int] IDENTITY(1,1) NOT NULL,
	[IdPedidoCompra] [int] NULL,
	[IdValoresCentroCusto] [int] NULL,
 CONSTRAINT [PK_PedidoCompraCentroCusto] PRIMARY KEY CLUSTERED 
(
	[IdPedidoCompraCentroCusto] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ValoresCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoCompra SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoCompraCentroCusto ADD CONSTRAINT
	FK_PedidoCompraCentroCusto_PedidoCompra FOREIGN KEY
	(
	IdPedidoCompra
	) REFERENCES dbo.PedidoCompra
	(
	IdPedidoCompra
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoCompraCentroCusto ADD CONSTRAINT
	FK_PedidoCompraCentroCusto_ValoresCentroCusto FOREIGN KEY
	(
	IdValoresCentroCusto
	) REFERENCES dbo.ValoresCentroCusto
	(
	IdValoresCentroCusto
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoCompraCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PedidoVendaCentroCusto](
	[IdPedidoVendaCentroCusto] [int] IDENTITY(1,1) NOT NULL,
	[IdPedidoVenda] [int] NULL,
	[IdValoresCentroCusto] [int] NULL,
 CONSTRAINT [PK_PedidoVendaCentroCusto] PRIMARY KEY CLUSTERED 
(
	[IdPedidoVendaCentroCusto] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ValoresCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoVenda SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoVendaCentroCusto ADD CONSTRAINT
	FK_PedidoVendaCentroCusto_PedidoVenda FOREIGN KEY
	(
	IdPedidoVenda
	) REFERENCES dbo.PedidoVenda
	(
	IdPedidoVenda
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoVendaCentroCusto ADD CONSTRAINT
	FK_PedidoVendaCentroCusto_ValoresCentroCusto FOREIGN KEY
	(
	IdValoresCentroCusto
	) REFERENCES dbo.ValoresCentroCusto
	(
	IdValoresCentroCusto
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoVendaCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
