SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PedidoCompraItemCentroCusto](
	[IdPedidoCompraItemCentroCusto] [int] IDENTITY(1,1) NOT NULL,
	[IdPedidoCompraItem] [int] NULL,
	[IdValoresCentroCusto] [int] NULL,
 CONSTRAINT [PK_PedidoCompraItemCentroCusto] PRIMARY KEY CLUSTERED 
(
	[IdPedidoCompraItemCentroCusto] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ValoresCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoCompraItem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoCompraItemCentroCusto ADD CONSTRAINT
	FK_PedidoCompraItemCentroCusto_PedidoCompraItem FOREIGN KEY
	(
	IdPedidoCompraItem
	) REFERENCES dbo.PedidoCompraItem
	(
	IdPedidoCompraItem
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoCompraItemCentroCusto ADD CONSTRAINT
	FK_PedidoCompraItemCentroCusto_ValoresCentroCusto FOREIGN KEY
	(
	IdValoresCentroCusto
	) REFERENCES dbo.ValoresCentroCusto
	(
	IdValoresCentroCusto
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoCompraItemCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PedidoVendaItemCentroCusto](
	[IdPedidoVendaItemCentroCusto] [int] IDENTITY(1,1) NOT NULL,
	[IdPedidoVendaItem] [int] NULL,
	[IdValoresCentroCusto] [int] NULL,
 CONSTRAINT [PK_PedidoVendaItemCentroCusto] PRIMARY KEY CLUSTERED 
(
	[IdPedidoVendaItemCentroCusto] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ValoresCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoVendaItem SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PedidoVendaItemCentroCusto ADD CONSTRAINT
	FK_PedidoVendaItemCentroCusto_PedidoVendaItem FOREIGN KEY
	(
	IdPedidoVendaItem
	) REFERENCES dbo.PedidoVendaItem
	(
	IdPedidoVendaItem
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoVendaItemCentroCusto ADD CONSTRAINT
	FK_PedidoVendaItemCentroCusto_ValoresCentroCusto FOREIGN KEY
	(
	IdValoresCentroCusto
	) REFERENCES dbo.ValoresCentroCusto
	(
	IdValoresCentroCusto
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PedidoVendaItemCentroCusto SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
