
using System;  
namespace ERP.ModelView
{

    public class vwDanfe
    { 
		public int Id { get; set; } 
        public int IdNotaFiscal { get; set; } 
        public int? ide_cUF { get; set; } 
        public string ide_natOp { get; set; } 
        public int? ide_indPag { get; set; } 
        public int? ide_mode { get; set; } 
        public int? ide_serie { get; set; } 
        public int? ide_nNF { get; set; } 
        public DateTime? ide_dEmi { get; set; } 
        public DateTime? ide_dSaiEnt { get; set; } 
        public int? ide_tpNF { get; set; } 
        public int? ide_cMunFG { get; set; } 
        public int? ide_tpImp { get; set; } 
        public int? ide_finNFe { get; set; } 
        public int? ide_tpEmis { get; set; } 
        public int? ide_procEmi { get; set; } 
        public string ide_verProc { get; set; } 
        public string ide_NFref { get; set; } 
        public string ide_CondPagDesc { get; set; } 
        public string TP_PESSOA { get; set; } 
        public string dest_CNPJ { get; set; } 
        public string dest_xNome { get; set; } 
        public string dest_xFant { get; set; } 
        public string dest_xlgr { get; set; } 
        public string dest_nro { get; set; } 
        public string dest_xCpl { get; set; } 
        public string dest_xBairro { get; set; } 
        public int? dest_cMun { get; set; } 
        public string dest_xMun { get; set; } 
        public string dest_UF { get; set; } 
        public string dest_CEP { get; set; } 
        public string dest_cPais { get; set; } 
        public string dest_xPais { get; set; } 
        public string dest_fone { get; set; } 
        public string dest_IE { get; set; } 
        public string dest_IESUF { get; set; } 
        public string dest_email { get; set; } 
        public int? indIEDest { get; set; } 
        public int? INF_ITEM { get; set; } 
        public string Prod_cProd { get; set; } 
        public string Prod_cEAN { get; set; } 
        public string Prod_xProd { get; set; } 
        public string Prod_NCM { get; set; }
        public string Prod_CEST { get; set; }
        public string Prod_ExTIPI { get; set; } 
        public string Prod_genero { get; set; } 
        public string Prod_CFOP { get; set; } 
        public string Prod_uCOM { get; set; } 
        public decimal? Prod_qCom { get; set; } 
        public decimal? Prod_vUnCom { get; set; } 
        public decimal? Prod_vProd { get; set; } 
        public string Prod_cEANTrib { get; set; } 
        public string Prod_uTrib { get; set; } 
        public decimal? Prod_qTrib { get; set; } 
        public decimal? Prod_vUnTrib { get; set; } 
        public decimal? Prod_vFrete { get; set; } 
        public int? Prod_vSeguro { get; set; } 
        public decimal? prod_Vdesc { get; set; } 
        public string Prod_DI { get; set; } 
        public string Prod_DetEspecifico { get; set; } 
        public string Prod_infAdProd { get; set; } 
        public string icms_orig { get; set; } 
        public string icms_CST { get; set; } 
        public int? icms_modBC { get; set; } 
        public int? icms_pRedBC { get; set; } 
        public decimal? icms_vBC { get; set; } 
        public decimal? icms_pICMS { get; set; } 
        public decimal? icms_vICMS { get; set; } 
        public int? icms_modBCST { get; set; } 
        public int? icms_pmVAST { get; set; } 
        public int? icms_pRedBCST { get; set; } 
        public decimal? icms_BCST { get; set; } 
        public decimal? icms_vICMSST { get; set; } 
        public decimal? icms_pICMSST { get; set; } 
        public string ipi_clEnq { get; set; } 
        public string ipi_CNPJProd { get; set; } 
        public string ipi_cSelo { get; set; } 
        public int? ipi_qSelo { get; set; } 
        public string ipi_cEnq { get; set; } 
        public string ipi_CST { get; set; } 
        public decimal? ipi_vBC { get; set; } 
        public decimal? ipi_pIPI { get; set; } 
        public decimal? ipi_vIPI { get; set; } 
        public int? ipi_qUnid { get; set; } 
        public int? ipi_vUnid { get; set; } 
        public string pis_CST { get; set; } 
        public int? pis_vBC { get; set; } 
        public decimal? pis_pPIS { get; set; } 
        public int? pis_vPIS { get; set; } 
        public int? pis_qBCProd { get; set; } 
        public int? pis_vAliqProd { get; set; } 
        public string cofins_CST { get; set; } 
        public int? cofins_vBC { get; set; } 
        public decimal? cofins_pCOFINS { get; set; } 
        public int? cofins_vCOFINS { get; set; } 
        public int? cofins_qBCProd { get; set; } 
        public int? cofins_vAliqProd { get; set; } 
        public decimal? tot_vBC { get; set; } 
        public decimal? tot_vICMS { get; set; } 
        public decimal? tot_vBCST { get; set; } 
        public decimal? tot_vST { get; set; } 
        public decimal? tot_vProd { get; set; } 
        public decimal? tot_vFrete { get; set; } 
        public decimal? tot_vSeg { get; set; } 
        public decimal? tot_vDesc { get; set; } 
        public decimal? tot_vII { get; set; } 
        public decimal? tot_vIPI { get; set; } 
        public decimal? tot_vPIS { get; set; } 
        public decimal? tot_vCOFINS { get; set; } 
        public decimal? tot_vOutro { get; set; } 
        public decimal? tot_vNF { get; set; } 
        public int? CodigoNF { get; set; } 
        public int? tra_modFrete { get; set; } 
        public string tra_transportadora { get; set; } 
        public string tra_retTransp { get; set; } 
        public string tra_veicTransp { get; set; } 
        public string tra_reboque { get; set; } 
        public string tra_vol { get; set; } 
        public string tra_CNPJ { get; set; } 
        public string tra_CPF { get; set; } 
        public string tra_xNome { get; set; } 
        public string tra_IE { get; set; } 
        public string tra_xEnder { get; set; } 
        public string tra_xMun { get; set; } 
        public string tra_UF { get; set; } 
        public string veic_Placa { get; set; } 
        public string veic_UF { get; set; } 
        public string veic_RNTC { get; set; } 
        public decimal? vol_qVol { get; set; } 
        public string vol_esp { get; set; } 
        public string vol_Marca { get; set; } 
        public string vol_nVol { get; set; } 
        public decimal? vol_pesoL { get; set; } 
        public decimal? vol_pesoB { get; set; } 
        public string vol_lacres { get; set; } 
        public string nroRecibo { get; set; }   
        public string Protocolo { get; set; } 
        public string dtRecebimento { get; set; }
        public string ChaveAut { get; set; }   
        public int? Ambiente { get; set; }      
        public string emi_CNPJ { get; set; } 
        public string emi_xNome { get; set; } 
        public string emi_xFant { get; set; } 
        public string emi_xLgr { get; set; } 
        public string emi_IE { get; set; } 
        public string emi_nro { get; set; } 
        public string emi_xCpl { get; set; } 
        public string emi_xBairro { get; set; } 
        public int? emi_cMun { get; set; } 
        public string emi_xMun { get; set; } 
        public string emi_UF { get; set; } 
        public string emi_CEP { get; set; } 
        public string emi_cPais { get; set; } 
        public string emi_xPais { get; set; } 
        public string emi_Fone { get; set; }  
        public string emi_IEST { get; set; } 
        public string emi_IM { get; set; } 
        public string emi_CNAE { get; set; } 
        public byte[] Logo { get; set; }
        public byte[] BarCode { get; set; }
        public string emi_CRT { get; set; }
        public string infAdic { get; set; }
        public string aaaa { get; set; }
        public int? IdProduto { get; set; }
        public int? IdNCM { get; set; }
        public int? IdUnidade { get; set; }
        public int? Conversao { get; set; }
    }
}
